name: ExtendedHorizons
version: ${version}
main: me.mapacheee.extendedhorizons.ExtendedHorizonsPlugin
api-version: '1.20'
folia-supported: true
description: ${description}
author: Mapacheee
website: https://github.com/mapacheee/extendedhorizons

depend: [packetevents]
softdepend: [PlaceholderAPI]

commands:
  extendedhorizons:
    description: Main ExtendedHorizons command
    usage: /<command> [subcommand]
    aliases: [eh, horizons, viewdistance, vd]
    permission: extendedhorizons.use

permissions:
  extendedhorizons.use:
    description: Basic permission to use ExtendedHorizons features
    default: true
  extendedhorizons.admin:
    description: Access to admin commands
    default: op
  extendedhorizons.max.*:
    description: Max distance override for /eh setme via extendedhorizons.max.<distance>
    default: false
