name: ExtendedHorizons
version: ${version}
main: me.mapacheee.extendedhorizons.ExtendedHorizonsPlugin
api-version: '1.20'
folia-supported: true
description: ${description}
author: Mapacheee
website: https://github.com/mapacheee/extendedhorizons
depend: [MapacheeeLib]

commands:
  extendedhorizons:
    description: Main ExtendedHorizons command
    usage: /<command>
    aliases: [eh]
    permission: extendedhorizons.use
    
permissions:
  extendedhorizons.use:
    description: Basic permission to use ExtendedHorizons
    default: true

