name: ExtendedHorizons
version: ${version}
main: me.mapacheee.extendedhorizons.ExtendedHorizonsPlugin
api-version: '1.21'
folia-supported: true
description: ${description}
author: Mapacheee
website: https://github.com/mapacheee/extendedhorizons

libraries:
 - org.xerial:sqlite-jdbc:3.51.1.0

depend: [packetevents]
softdepend: [LuckPerms, PlaceholderAPI]

commands:
  extendedhorizons:
    description: Main ExtendedHorizons command
    usage: /<command> [subcommand]
    aliases: [eh, horizons, viewdistance, vd]
    permission: extendedhorizons.use

permissions:
  extendedhorizons.use:
    description: Basic permission to use ExtendedHorizons features
    default: true
  extendedhorizons.admin:
    description: Access to admin commands
    default: op
  extendedhorizons.bypass.limits:
    description: Bypass network and performance limits
    default: false
